#!/bin/bash

Interface="enp4s0"

R1="$(cat /sys/class/net/$Interface/statistics/rx_bytes)"
T1="$(cat /sys/class/net/$Interface/statistics/tx_bytes)"

sleep 1

R2="$(cat /sys/class/net/$Interface/statistics/rx_bytes)"
T2="$(cat /sys/class/net/$Interface/statistics/tx_bytes)"

TBPS="$(expr $T2 - $T1)"
RBPS="$(expr $R2 - $R1)"
TMBPS="$(expr $TBPS / 121072)"
RMBPS="$(expr $RBPS / 121072)"

iconrx=""
icontx=""

printf "[ %s %s  %s %s ]\\n" "$iconrx" "$RMBPS Mbit" "$icontx" "$TMBPS Mbit"
